# Generated by Django 4.1 on 2023-05-03 12:50

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=500)),
                ('meta_desc', models.CharField(max_length=500)),
                ('url_slug', models.SlugField(max_length=500, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('toc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Table of Content')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='guides_featured_image/')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewed_at', models.DateTimeField()),
                ('auto_gen_toc', models.BooleanField(default=True, verbose_name='Auto Generate Table of Content')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='Draft', max_length=20)),
                ('category_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_created_by', to='web_app.doctor')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.business')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_reviewed_by', to='web_app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='BlogMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='thing', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('same_as', models.URLField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='guides.blog')),
            ],
        ),
        migrations.CreateModel(
            name='BlogCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=500)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='guides.blog')),
            ],
        ),
        migrations.CreateModel(
            name='BlogAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='thing', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('same_as', models.URLField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abouts', to='guides.blog')),
            ],
        ),
    ]
