# Generated by Django 4.1 on 2023-05-03 12:49

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('map_id', models.URLField(max_length=1000)),
                ('additional_Type', models.URLField(blank=True, null=True)),
                ('medical_Specialty', models.CharField(max_length=255)),
                ('payment_Accepted', models.CharField(max_length=255)),
                ('hasMap', models.URLField(max_length=1000)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('isAcceptingNewPatients', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='yes', max_length=255)),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('AlternateName', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('disambiguatingDescription', models.TextField(blank=True, null=True)),
                ('foundingDate', models.CharField(max_length=255)),
                ('SameAs', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencyName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_desc', models.CharField(max_length=255)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='featured_images/')),
                ('top_img', models.ImageField(blank=True, null=True, upload_to='images')),
                ('top_img_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('notice', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('displayimage', models.ImageField(blank=True, null=True, upload_to='images')),
                ('aboutDescript', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('meetteam', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('afterTeamContent', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomSiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('site_url', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('favicon', models.ImageField(upload_to='logo/')),
                ('nav_brand_html', ckeditor_uploader.fields.RichTextUploadingField()),
                ('nav_html', ckeditor_uploader.fields.RichTextUploadingField()),
                ('footer_html', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('nav_icon_html', models.CharField(blank=True, max_length=255, null=True)),
                ('social_links_html', models.TextField(blank=True, null=True)),
                ('script', models.TextField(blank=True, null=True)),
                ('copyright_text', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('additional_name', models.CharField(blank=True, max_length=255, null=True)),
                ('family_name', models.CharField(blank=True, max_length=255, null=True)),
                ('given_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctor_images/')),
                ('image_caption', models.CharField(blank=True, max_length=255, null=True)),
                ('honorific_prefix', models.CharField(default='Dr.', max_length=20)),
                ('honorific_suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('job_title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('disambiguating_description', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_type', models.CharField(blank=True, max_length=255, null=True)),
                ('is_part_of', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='Draft', max_length=20)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.business')),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage/', verbose_name='large image')),
                ('text', models.TextField(verbose_name='text on lagre image')),
                ('about_us_heading', models.CharField(default='About Us', max_length=255)),
                ('about_us_image', models.ImageField(upload_to='homepage/', verbose_name='about-us image')),
                ('about_us_text', ckeditor.fields.RichTextField(verbose_name='about-us text')),
                ('service_heading', models.CharField(default='SERVICES', max_length=255)),
                ('service_subheading', models.CharField(default='Excellent Medical Services', max_length=255)),
                ('doctor_heading', models.CharField(default='Meet Our Team', max_length=255)),
                ('doctor_subheading', models.CharField(default='Qualified Healthcare Professionals', max_length=255)),
                ('testimonial_heading', models.CharField(default='TESTIMONIAL', max_length=255)),
                ('testimonial_subheading', models.CharField(default='Patients Say About Our Services', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KnowsLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('additional_type', models.CharField(blank=True, help_text='https://en.wikipedia.org/wiki/Clear_aligners', max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('disambiguating_description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='images')),
                ('image_caption', models.CharField(max_length=255)),
                ('potential_action', models.CharField(blank=True, help_text='Call for a free consultation', max_length=255, null=True)),
                ('is_part_of', models.URLField(default='https://soumyahospitals.com', max_length=255)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='content will display in frontend only')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='Draft', max_length=20)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reviewed_by', to='web_app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='TESTIMONIAL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/testimonial')),
                ('Comment', models.TextField()),
                ('customerName', models.CharField(max_length=255)),
                ('homePage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.homepage')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMentions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('same_as', models.URLField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('same_as', models.URLField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.service')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=255)),
                ('timming', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.business')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='ImageObject', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('url', models.ImageField(upload_to='images/')),
                ('creator', models.CharField(max_length=255)),
                ('contentLocation', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.business')),
            ],
        ),
        migrations.CreateModel(
            name='Haspart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='CreativeWork', max_length=255)),
                ('url', models.URLField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.business')),
            ],
        ),
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='GeoCoordinates', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('postalCode', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.business')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorWorksForOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('year_range', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_for_organizations', to='web_app.doctor')),
            ],
            options={
                'verbose_name': 'Works for Organization',
                'verbose_name_plural': 'Works for Organizations',
            },
        ),
        migrations.CreateModel(
            name='DoctorSocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='web_app.doctor')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
            },
        ),
        migrations.CreateModel(
            name='DoctorOccupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='web_app.doctor')),
            ],
            options={
                'verbose_name': 'Occupation',
                'verbose_name_plural': 'Occupations',
            },
        ),
        migrations.CreateModel(
            name='DoctorMemberOfOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_of_organizations', to='web_app.doctor')),
            ],
            options={
                'verbose_name': 'Member of Organization',
                'verbose_name_plural': 'Member of Organizations',
            },
        ),
        migrations.CreateModel(
            name='DoctorKnowsLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knows_languages', to='web_app.doctor')),
            ],
            options={
                'verbose_name': 'Knows Language',
                'verbose_name_plural': 'Knows Languages',
            },
        ),
        migrations.CreateModel(
            name='DoctorExtraInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('ordering', models.PositiveIntegerField(default=1)),
                ('visibility', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_informations', to='web_app.doctor')),
            ],
            options={
                'verbose_name': 'Extra Information',
                'verbose_name_plural': 'Extra Informations',
            },
        ),
        migrations.CreateModel(
            name='DoctorExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text'), ('thing', 'Thing')], default='text', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise', to='web_app.doctor')),
            ],
            options={
                'verbose_name': 'Expertise',
                'verbose_name_plural': 'Expertise',
            },
        ),
        migrations.CreateModel(
            name='DoctorEducationalOccupationalCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='web_app.doctor')),
            ],
            options={
                'verbose_name': 'Educational Occupational Credential',
                'verbose_name_plural': 'Educational Occupational Credentials',
            },
        ),
        migrations.CreateModel(
            name='DoctorColleague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colleague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.doctor')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleagues', to='web_app.doctor')),
            ],
            options={
                'verbose_name': 'Colleague',
                'verbose_name_plural': 'Colleagues',
            },
        ),
        migrations.CreateModel(
            name='DoctorAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='web_app.doctor')),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
            },
        ),
        migrations.CreateModel(
            name='DoctorAlumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, verbose_name='college/university name')),
                ('url', models.URLField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='web_app.doctor')),
            ],
            options={
                'verbose_name': 'Alumni College or University',
                'verbose_name_plural': 'Alumni College or University',
            },
        ),
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='ContactPoint', max_length=255)),
                ('contactType', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.business')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='curreny_Accepted',
            field=models.ManyToManyField(to='web_app.currency'),
        ),
        migrations.AddField(
            model_name='business',
            name='knows_language',
            field=models.ManyToManyField(to='web_app.knowslanguage'),
        ),
        migrations.CreateModel(
            name='AreaServed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='City', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.business')),
            ],
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('postalCode', models.CharField(max_length=255)),
                ('addressRegion', models.CharField(max_length=255)),
                ('addressCountry', models.CharField(max_length=255)),
                ('streetAddress', models.CharField(max_length=500)),
                ('addressLocality', models.CharField(max_length=500)),
                ('business', models.ForeignKey(default='PostalAddress', on_delete=django.db.models.deletion.CASCADE, to='web_app.business')),
            ],
        ),
    ]
